### PR TITLE
MBS-5452: Support multiple lyric language values for works

### PR DESCRIPTION
**Pull request by mwiencek**
Also keeps the old single-language fields for compatibility.

### CODE REVIEW

**Comment by mwiencek** [comment]
I have a test search server running now, so here's an example of this: https://test.musicbrainz.org/ws/2/work/?query=wid:bb8fc7b2-e48d-414c-a748-474f27746d31

Note: I had to make a lot of docker changes to even be able to deploy a test search server/indexer, since many things were hardcoded (configuration, but also the actual code...I guess it downloaded binaries from ftp previously, but now it builds it from the repo).

**Comment by mayhem** [comment]
Hmmm. There were reasons for both of these...

1) Many moons ago we got the advice that we should never run openjdk in a high traffic production environment, which is why I specifically chose an oracle based image.
2) The images are put up on FTP in order to let others download them. No biggie, we can move them there manually.

Does this need to be released at the same time as the scheme change stuff? Or could we release it tomorrow (or later) in order to not have to push this through before the release today?

**Comment by mwiencek** [comment]
Definitely doesn't need to be released today, I'll put this in another branch.

Thanks for passing down the JDK advice. Actually, I wasn't sure which to use, since the indexer uses oracle-jdk, but the server uses a jetty image based on openjdk. I'll switch it to the Oracle-based JDK in the new Dockerfiles.

If we could copy the JAR/WAR files to FTP manually, or just have whatever script is doing that pull them from the docker image automatically, that would be great, 'cause it's really useful to be able to build an image based on the code/branch you have checked out otherwise.

**Comment by mayhem** [comment]
OK, looks good to me, it builds and tests pass. Code looks believable.

**Pull request merged**
